@startuml
'https://plantuml.com/class-diagram

App --|> display
App --|> parse
parse --|> prompt
App --|> readFile

class display{
+output();
}
class parse {
+data();
}
class prompt{
+item();
}
class readFile{
+read();
}

@enduml