@startuml
'https://plantuml.com/class-diagram

App --|> prompt
App --|> readFile
App --|> swapWord
App --|> writeFile

class readFile{
+read();
}
class swapWord {
+replace();
}
class prompt{
+askFileName();
}
class writeFile{
+write();
}
@enduml