@startuml
'https://plantuml.com/class-diagram

App --|> countOccurrences
App --|> display
App --|> parse
App --|> readFile

class readFile{
+read();
}
class countOccurrences{
+count();
}
class display{
+histogram();
}
class parse{
+separateWord();
}

@enduml